// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

const AUTH_COOKIE_MAX_AGE = 60 * 60 * 24 * 30;
let allowSessionWrite = false;
let allowSessionClear = false;

const shouldUseRecoveryStorage = () => {
  if (typeof window === "undefined") return false;
  const url = new URL(window.location.href);
  const hashParams = new URLSearchParams(url.hash.replace(/^#/, ""));
  return (
    url.pathname.includes("/recovery") ||
    hashParams.get("type") === "recovery" ||
    hashParams.has("access_token") ||
    hashParams.has("refresh_token")
  );
};

const isCodeVerifierKey = (key: string) => key.includes("code-verifier");

const isAuthTokenKey = (key: string) => key.startsWith("sb-") && key.includes("auth-token");

const readCookie = (name: string) => {
  if (typeof document === "undefined") return null;
  const encodedName = encodeURIComponent(name);
  const match = document.cookie.split("; ").find((part) => part.startsWith(`${encodedName}=`));
  if (!match) return null;
  return decodeURIComponent(match.substring(encodedName.length + 1));
};

const writeCookie = (name: string, value: string) => {
  if (typeof document === "undefined") return;
  const encodedName = encodeURIComponent(name);
  const encodedValue = encodeURIComponent(value);
  const secure = window.location.protocol === "https:" ? "; Secure" : "";
  document.cookie = `${encodedName}=${encodedValue}; Path=/; Max-Age=${AUTH_COOKIE_MAX_AGE}; SameSite=Lax${secure}`;
};

const deleteCookie = (name: string) => {
  if (typeof document === "undefined") return;
  const encodedName = encodeURIComponent(name);
  const secure = window.location.protocol === "https:" ? "; Secure" : "";
  document.cookie = `${encodedName}=; Path=/; Max-Age=0; SameSite=Lax${secure}`;
};

export const enableAuthCookieWriteOnce = () => {
  allowSessionWrite = true;
};

export const resetAuthCookieWrite = () => {
  allowSessionWrite = false;
};

export const enableAuthCookieClearOnce = () => {
  allowSessionClear = true;
};

export const resetAuthCookieClear = () => {
  allowSessionClear = false;
};

export const hasAuthCookieSession = () => {
  if (typeof document === "undefined") return false;
  if (!document.cookie) return false;
  return document.cookie.split("; ").some((part) => {
    const [rawName] = part.split("=");
    const name = decodeURIComponent(rawName || "");
    return name.startsWith("sb-") && name.includes("auth-token");
  });
};

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: {
      getItem: (key: string) => {
        const cookieValue = readCookie(key);
        if (cookieValue) return cookieValue;
        if (isCodeVerifierKey(key)) {
          return sessionStorage.getItem(key);
        }
        return sessionStorage.getItem(key);
      },
      setItem: (key: string, value: string) => {
        // Code verifiers should always be written to cookies
        if (isCodeVerifierKey(key)) {
          writeCookie(key, value);
          return;
        }
        
        // Auth tokens should be persisted to cookies for cross-tab sync and persistence
        // This includes initial tokens and refreshed tokens
        if (isAuthTokenKey(key)) {
          writeCookie(key, value);
          return;
        }
        
        // During login/signup, write to cookies
        if (allowSessionWrite) {
          allowSessionWrite = false;
          writeCookie(key, value);
          return;
        }
        
        // During recovery flow, use sessionStorage
        if (shouldUseRecoveryStorage()) {
          sessionStorage.setItem(key, value);
          return;
        }
        
        // Default: store in sessionStorage
        sessionStorage.setItem(key, value);
      },
      removeItem: (key: string) => {
        sessionStorage.removeItem(key);
        if (isCodeVerifierKey(key)) {
          deleteCookie(key);
        }
        if (!allowSessionClear) return;
        allowSessionClear = false;
        deleteCookie(key);
      },
    },
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: "pkce",
  },
  global: {
    headers: { "x-client-info": "mini-ats" },
  },
  db: {
    schema: "public",
  },
});
